### PR TITLE
Add isMariaDb public function to the MySQL drivers

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for no issue. Just for future use.

### Summary of Changes

As the title sais.

### Testing Instructions

Code review.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by mbabker** [comment]
These methods need to call `$this->connect()` first because this check can only be made after a connection is established (the API uses lazy connections and doesn't arbitrarily open a connection when you instantiate the driver, so `(new MysqlDriver)->isMariaDb();` with a MariaDB backend would report false before connect is called and true afterwards).

**Comment by richard67** [comment]
@mbabker I see. But then the same applies for the "hasUTF8mb4Support", too, which is above the new function, right? Shall I correct both or only the new one?

**Comment by mbabker** [comment]
Just the new one for now.

**Comment by mbabker** [comment]
(While technically it's true utf8mb4 can only be reliably determined after the connection is made, before connection it can be assumed from the configuration given to the driver, whereas with MariaDB checks there's just no way to know anything without a connection, all this to say the has method should probably be fixed but it's not as "critically" broken as this one is without a connection)

**Comment by richard67** [comment]
Thank for the explanation. Yes, that is the difference.

**Pull request merged**
