### PR TITLE
Handle union in DatabaseQuery

### PR DESCRIPTION
**Pull request by jbanety**
Build UNION queries like this : 

``` php
$q1 = $db->getQuery(true);
$q2 = $db->getQuery(true);
$q2 = $db->getQuery(true);

$q1->select('a.col1, a.col2, a.col3')
   ->from('test1 AS a')
   ->order('a.col1 ASC');

$q2->select('b.col1, b.col2, b.col3')
   ->from('test2 as b')
   ->order('b.col1 DESC');

$q3->select('c.col1, c.col2, c.col3')
   ->from('test3 as c');

$q1->union($q2)->union($q3);
```

SQL output : 

``` sql
( SELECT a.col1, a.col2, a.col3 FROM test1 AS a ORDER BY a.col1 ASC) UNION ( SELECT b.col1, b.col2, b.col3 FROM test2 as b ORDER BY b.col1 DESC) UNION ( SELECT c.col1, c.col2, c.col3 FROM test3 as c)
```

### CODE REVIEW

**Comment by jbanety** [comment]
This can be improved to add global `ORDER` and `LIMIT` clauses and so on.

**Comment by photodude** [comment]
@jbanety can you rebase and fix the Code style and unit test issues in your PR?

**Comment by csthomas** [comment]
Take a look  and test a new PR https://github.com/joomla-framework/database/pull/116

**Comment by mbabker** [comment]
Closing in favor of #116

**Pull request closed without merging**
