### PR TITLE
Run tests against php 7 and HHVM

### PR DESCRIPTION
**Pull request by photodude**
- Allow php 7 and HHVM to fail

### CODE REVIEW

**Comment by mbabker** [comment]
We're actually doing this on all the package 2.0 branches already (https://github.com/joomla-framework/database/blob/2.0-dev/.travis.yml).

**Comment by photodude** [comment]
@mbabker Is there any reason not to do this on the existing branches?

**Comment by mbabker** [comment]
I was thinking at the time to focus on 2.0 dev and B/C breaks could be more easily dealt with there compared to 1.x.  Not to say 1.x code doesn't work with HHVM or PHP7 but it's easier to deal with compatibility issues in 2.0 then back port as able (for me at least).

**Comment by photodude** [comment]
I can see that. 
I was thinking since I think the CMS uses the 1.x branches of the framework currently, making the php7 and hhvm tests visible in the 1.x branches might be helpful. It would also help when/if B/C back ports from the 2.x branch occurs.

**Comment by mbabker** [comment]
Ya good point

**Comment by photodude** [comment]
Closing as this was implemented via a different PR

**Pull request closed without merging**
