### PR TITLE
Remove the default table prefix (Fix #5)

### LINKED ISSUE #5: Remove 'jos_' default prefix
We need to allow for no database prefix here:

https://github.com/joomla-framework/database/blob/master/src/DatabaseDriver.php#L401

This causes a b/c problem so we should sync this with a 2.0 release.

### PR DESCRIPTION
**Pull request by mbabker**
See #5

### CODE REVIEW

**Comment by mbabker** [comment]
@wilsonge @eddieajau Yay or nay?  This would be rebased to the 2.0 branch if yay.

**Comment by wilsonge** [comment]
yay

**Comment by eddieajau** [comment]
Can you add a test to check that an empty prefix is allowed?

**Comment by mbabker** [comment]
Done

**Comment by eddieajau** [comment]
If it passes, it's a :+1: from me.

**Pull request merged**
