### PR TITLE
Port new functions from CMS

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue #

### Summary of Changes
- Add findInSet() from https://github.com/joomla/joomla-cms/pull/12642
- Add unionAll() from https://github.com/joomla/joomla-cms/commit/f3860def9e0c5b266471e585e4e5abc2e66f9cf7
- Add dateAdd() method from https://github.com/joomla/joomla-cms/commit/a2f38090bd482b872cb9db099820abbc854865e2
- ports parts of https://github.com/joomla/joomla-cms/pull/6188

### Testing Instructions
code review

### Documentation Changes Required
new methods added, add these to documentation

### CODE REVIEW

**Comment by photodude** [comment]
@alikon this PR should cover porting your changes from the CMS to the framework. Please review.
(we should also get Unit tests done for these functions at some point)

**Comment by alikon** [comment]
seems ok to me

**Comment by photodude** [comment]
@csthomas, @mbabker, @alikon 
Should we revert the `findInSet()` addition in the framework as we are in the CMS? 
See the following
- https://github.com/joomla/joomla-cms/issues/13263
- https://github.com/joomla/joomla-cms/pull/14020

**Comment by csthomas** [comment]
I advice to revert it.

**Comment by mbabker** [comment]
It's already been tagged here, so the best we can do is deprecate it.

**Comment by wilsonge** [comment]
This worked at the CMS environment in postgres and mysql (untested in mssql), and at a framework level it probably deserves to be supported

**Pull request merged**
