### PR TITLE
[2.0] Update query monitor to log bound parameters

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #214

### Summary of Changes

As noted in #214, the monitor also should be able to log the query parameters.

### Documentation Changes Required

yeah, if there any

### CODE REVIEW

**Comment by HLeithner** [comment]
thanks for the pr do we have already support in the joomla debug tools?

**Comment by Fedik** [comment]
no, but I have plan to do it later, after query monitor will be fixed here ;)

**Comment by wilsonge** [comment]
Thanks!

**Comment by Fedik** [comment]
how I can use this in my pull request to joomla/joomla-cms? :)

**Comment by zero-24** [comment]
It should be an composer update on the 4.0-dev branch so you get the latest version of the joomla/database package.

**Pull request merged**
