### PR TITLE
Disable xdebug since travis is not doing code coverage.

### PR DESCRIPTION
**Pull request by photodude**
Merge by code review, composer should no longer bark about xdebug running.

### CODE REVIEW

**Comment by mbabker** [comment]
So two things:

1) How much are we really gaining here turning off XDebug?
2) At some point I'd like to have all of the repos wired in with Scrutinizer (some of them are), and that does collect code coverage.

**Comment by photodude** [comment]
1) This cuts a few seconds off the travis builds, possibly more.
2) This only affects the travis builds
3) +1 for Scrutinizer,

**Comment by mbabker** [comment]
The way we have things set up (see https://github.com/joomla-framework/date/blob/2.0-dev/.travis.yml as an example), the coverage is collected on Travis and sent to Scrutinizer.  So we'd really just be reverting this as soon as we finished setting things up (if it happens).

**Comment by photodude** [comment]
So we'll need to re-enable xdebug on the CMS if/when Scrutinizer is set up there....

**Pull request closed without merging**
