### PR TITLE
LimitableInterface inclusion is missing

### PR DESCRIPTION
**Pull request by jbanety**
the same as previous one.

### CODE REVIEW

**Comment by mbabker** [comment]
This will get applied when master gets merged onto here (I generally do that pretty quick now), so I'm closing this PR and it'll fix itself with the next merge.

**Comment by jbanety** [comment]
Doh ! I'm using 2.0-dev in my projects... I'm waiting for your merge :)
Thanks.

**Comment by mbabker** [comment]
I went ahead and merged it over for you 😄

**Comment by jbanety** [comment]
Thank you very much !!!

**Pull request closed without merging**
